// Система организаций	

#define NONE				0
#define ADMINISTRATION		1
#define HEALTH_SOUTH		2
#define HEALTH_ARZAMAS		3
#define CNN					4
#define ROADPOLICE			5
#define PATROLPOLICE		6
#define SERVICE_SECURITY	7
#define SAIL_ARMY			8
#define OREHOV_OPG			9
#define IZMAIL_OPG			10
#define MEDVED_OPG			11
#define TAMBOV_OPG			12


enum FracName { 
	NONE_NAME[]					=		"Нет",
	ADMINISTRATION_NAME[] 		=		"Администрация Области",
	HEALTH_SOUTH_NAME[] 		=		"Городская Больница г.Южного",
	HEALTH_ARZAMAS_NAME[]  		=		"Городская Больница г.Арзамас",
	CNN_NAME[] 					=		"Средства Массовой Информации",
	ROADPOLICE_NAME[] 			=		"Дорожно Постовая Служба",
	PATROLPOLICE_NAME[] 		=		"Патрульно Постовая Служба",
	SERVICE_SECURITY_NAME[] 	= 		"Федеральная Служба Безопасности",
	SAIL_ARMY_NAME[] 			=  		"Военно Морской Флот",
	OREHOV_OPG_NAME[] 			=		"Ореховская ОПГ",
	IZMAIL_OPG_NAME[] 			=  		"Измайловская ОПГ",
	MEDVED_OPG_NAME[] 			=		"Медведковская ОПГ",
	TAMBOV_OPG_NAME[] 			=		"Тамбовская ОПГ"
};