/* 

	??? ???? ? ??? ??? ? ??? ???? ???     ?? ??? ???? ??? 
	??? ???? ? ??? ??? ? ??? ???? ???     ?? ??? ???? ??? 
	??? ???? ? ??? ??? ? ??? ???? ???     ?? ??? ???? ??? 

*/

#define COLOR_WHITE_H            FFFFFF
#define COLOR_WHITE_L            0xFFFFFFFF
#define COLOR_WHITE_S            "{FFFFFF}"

#define COLOR_BLUE_H            0366FC
#define COLOR_BLUE_L            0x0366FCFF

#define COLOR_RED_H             FF0000
#define COLOR_RED_L             0xFF0000FF

#define COLOR_ADM_H             EC4646
#define COLOR_ADM_L             0xEC4646FF

#define COLOR_ADMIN_H           006000
#define COLOR_ADMIN_L           0x006000FF

#define COLOR_SYSTEM_H          6B6B6B
#define COLOR_SYSTEM_L          0x6B6B6BFF

#define COLOR_PURPLE_H          F398F0
#define COLOR_PURPLE_L          0xF398F0FF

#define COLOR_GRAY          #DFDFDF
#define COLOR_GRAY_L		0xDFDFDFFF
#define COLOR_GRAY_S		"{DFDFDF}"

#define COLOR_ADM 			#EC4646
#define COLOR_ADM_L			0xEC4646FF
#define COLOR_ADM_S			"{EC4646}"

#define COLOR_ORANGE		#FF4500
#define COLOR_ORANGE_L 		0xFF4500FF
#define COLOR_ORANGE_S		"{FF4500}"

#define COLOR_YELLOW 		#FFFF00
#define COLOR_YELLOW_L		0xFFFF00FF
#define COLOR_YELLOW_S		"{FFFF00}"

#define COLOR_HAKI			#F0E68C
#define COLOR_HAKI_L		0xF0E68CFF
#define COLOR_HAKI_S		"{F0E68C}"

#define COLOR_CYAN			#00FFFF
#define COLOR_CYAN_L		0x00FFFFFF
#define COLOR_CYAN_S		"{00FFFF}"

#define COLOR_CHOCOLATE 	#D2691E
#define COLOR_CHOCOLATE_L 	0xD2691EFF
#define COLOR_CHOCOLATE_S	"{D2691E}"

#define COLOR_GREEN			#008000
#define COLOR_GREEN_L		0x008000FF
#define COLOR_GREEN_S		"{008000}"

new global[1024]; 


// LANGUAGE
#define RUSSIAN				0 // default
#define ENGLISH				1
#define UKRAINIAN			2
#define POLISH				3
#define CHINESE				4
#define JAPAN				5	


